apiVersion: apps/v1
kind: Deployment
metadata: 
  name: django
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchlabels:
      app: backend
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait for progress
        image: busybox
        command: ['sh','-c','until nc -z postgres-svc 5432;do sleep 1;done;']
      containers:
        - name: django
          image: ghanatava/django
          envFrom: 
            - configMapRef:
                name: confmap
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static
              mountPath: static
    volumeClaimTemplates:
      - metadata:
          name: static-pvc
        spec:
          accessModes: ["ReadWriteMany"]
          storageClassName: "standard"
          resource:
            requests:
              storage: 1Gi
            limits:
              storage: 2Gi
          
---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
spec:
  selector:
    app: django
  ports:
    - potocol: TCP
      port: 80
      targetPort: 8000
  
      
