apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 2
  serviceName: "postgres-svc"
  selector:
    matchLabel:
      labels:
        app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        envFrom:
          - configMapRef:
            name: confmap
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
    
    volumeClaimTemplates:
      - metadata: 
          name: postgres-storage
        spec:
          accessModes: ["ReadWriteMany"]
          storageClassName: "postgres-sc"
          resource: 
            requests: 
              storage: 10Gi
            limits:
              storage: 12Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-sc
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFristConsumer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  ports:
    - port: 80
      name: postgres
  clusterIP: None
  selector:
    app: postgres