apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 2
  serviceName: "postgres-svc"
  selector:
    matchLabel:
      labels:
        app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        envFrom:
          - configMapRef:
            name: confmap
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
    
    volumeClaimTemplates:
      - metadata: 
          name: postgres-storage
        spec:
          accessModes: ["ReadWriteMany"]
          storageClassName: "standard"
          resource: 
            requests: 
              storage: 10Gi
            limits:
              storage: 12Gi
            