apiVersion: batch/v1
kind: Job
metadata:
  name: react-build
spec:
  template:
    spec:
      containers:
      - name: react
        image: ghanatava/react
        command: ["npm","run","build"]
        volumeMounts:
        - name: frontend
          mountPath: /app/build
      restartPolicy: Never
  backoffLimit: 4
  volumeClaimTemplates:
    - metadata:
        name: frontend-pvc
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: "standard"
        resource: 
          requests:
            storage: 1Gi
          limits:
            storage: 2Gi